name: Compile Latex and Release PDF

# Controls when the workflow will run
on:
  push:
    tags:
      - '*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Compile Section 1
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./1-bayesian-probability-modeling
          root_file: main.tex

      - name: Compile Section 2
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./2-regression-models
          root_file: main.tex

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Section 1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./1-bayesian-probability-modeling/main.pdf
          asset_name: 1-bayesian-probability-modeling.pdf
          asset_content_type: pdf

      - name: Upload Section 2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./2-regression-models/main.pdf
          asset_name: 2-regression-models.pdf
          asset_content_type: pdf
